spring:
  data:
    mongodb:
      host: payment-db
  kafka:
    bootstrap-servers: kafka-service:9092
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8080